project:
  type: website
  output-dir: docs
  title: "Zoomalong"
  # authors:
  #   - name: Gary Newport
  #     url: https://zoomalong.co.uk
  # vars:
  #   years: "2020-`r format(Sys.Date(), '%Y')`"
  #   github-url: "newportg.github.io/zoomalong"
  #   pgp:
  #     key: "https://zoomalong.co.uk/pgp-key.txt"
  #     fingerprint: "A2C1 3E8D 0F3B 1B8D 6D2E  9DDF 2C0D 7E1D 0F4B A3C6" # GPG key fingerprint for Gary Newport    

website:
  title: "Zoomalong"
  navbar:
    left:
      # - href: index.qmd
      #   text: Home
      - text: "Now!"
        href: Content/Current/index.qmd      
      - text: "Journal"
        href: Content/Journal/index.qmd
      - text: "Calendar Template"
        href: Content/Research/index.qmd    
      # - text: "Books"
      #   href: Content/Books/index.qmd    
  
    right:
      - text: "{{< iconify bi envelope size=1.1em title='E-mail' >}}"
        href: "mailto:Gary.newport@zoomalong.co.uk"
      - text: "{{< iconify bi github size=1.1em title='GitHub' >}}"
        href: https://github.com/newportg
        rel: me
      - text: "{{< iconify bi linkedin size=1.1em title='LinkedIn' >}}"
        href: https://uk.linkedin.com/in/garynewport
        rel: me
  
  page-footer:
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} {{< var years >}} Gary Newport</span>
      <span class="faux-block">All content licensed under<br>[{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} Creative Commons CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)</span>      
    # center: |
    #   <span class="faux-block">{{< fa key >}} [PGP public key]({{< var pgp.key >}}) &emsp; {{< fa fingerprint >}} Fingerprint:</strong><br><span class="fingerprint">{{< var pgp.fingerprint >}}</span></span>
    right: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>
      <span class="faux-block">[View the source at {{< fa brands github >}} GitHub]({{< var github-url >}})</span>
  
  sidebar:
    - id: id-QuartoWebBook
      title: "Quarto Web Book"
      contents:
        - text: "Quarto Web Book Introduction"
          href: Content/Journal/posts/QuartoWebBook/index.html
        - text: "Chapter 1"
          href: Content/Journal/posts/QuartoWebBook/chapter1.html
        - text: "Chapter 2"
          href: Content/Journal/posts/QuartoWebBook/chapter2.html
          
    - id: id-AIDrivenCodeDevelopement
      title: "AI Driven Code Developement"
      contents:
        - text: "AI Driven Code Developement Introduction"
          href: Content/Journal/posts/AIDrivenCodeDevelopement/index.html
        - text: "CARE Framework"
          href: Content/Journal/posts/AIDrivenCodeDevelopement/CARE.html
        - text: "CARE Example"
          href: Content/Journal/posts/AIDrivenCodeDevelopement/CAREexample.html
        - text: "Spec-kit"
          href: Content/Journal/posts/AIDrivenCodeDevelopement/spec-kit.html
        - section: "VSCode"
          href: Content/Journal/posts/AIDrivenCodeDevelopement/VSCode.html
          contents:
            - text: "Podman"
              href: Content/Journal/posts/AIDrivenCodeDevelopement/Podman.html
            - text: "Dev Containers"
              href: Content/Journal/posts/AIDrivenCodeDevelopement/DevContainers.html

format:
  html:
    theme: 
      - html/gmn.scss
    grid: 
      body-width: 900px
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai

filters:
  - plantuml-diagram
  - quarto-kroki



